# Copyright (c) 2019-2020-2021 Luca Cappa
# Copyright (c) 2021 AICDG
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Build with CMake
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            cxx: cl.exe
            cc: cl.exe

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set Compiler Environment
        uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.243.0
          cache: true

      - name: Run CMake+Ninja
        uses: lukka/run-cmake@v3
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '--config RelWithDebInfo -j 2'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'